### ISSUE TITLE
 pam/etc/profile.d/sshpwd.sh need gettext-base

### ISSUE THREAD

**Issue by BjoernSch** [raspberrypi-ui/pam#1]
It calls "gettext.sh" so every user gets an error on login if "gettext-base" is not installed.
Please add this to the dependencies in the control file, package name is "libpam-chksshpwd".
It would also be better to call "gettext.sh" with the full path, which is /usr/bin/gettext.sh.

**Comment by spl237** [comment]
Raspbian images should all have gettext installed, as it is a fundamental requirement for internationalisation support in the desktop - I'm puzzled as to why you would have uninstalled it? If it's not present, a lot of things are likely to break.

Nonetheless, you are correct that it should be a dependency of the package - I'll add it in the next release.

**Comment by BjoernSch** [comment]
We use pi-gen to generate a custom image. There pam-chksshpwd gets installed in Stage 2 which is hopefully the same as the official -lite image.
This error should exist there too, but the current official image build is a little bit too old, and I think this package is not included there yet (I'm just judging by the timestamp, so I may be wrong).

**Comment by spl237** [comment]
OK, that makes sense. You're right that the chkpasswd module isn't in the lite image yet, so we may not have seen this. We ought to be including gettext in the lite image anyway - I'll check that.

**Comment by spl237** [comment]
Dependency added to package; it'll be in apt in the next day or so.
